#!/usr/bin/env bash

# TODO: Run brew ... here.

# Screenshots.
mkdir ~/Pictures/Screenshots
defaults write com.apple.screencapture location ~/Pictures/Screenshots
defaults write com.apple.screencapture name "Screenshot"
defaults write com.apple.screencapture disable-shadow -bool true
defaults write com.apple.screencapture show-thumbnail -bool false
killall SystemUIServer

# Keyboard.
defaults write -g NSAutomaticSpellingCorrectionEnabled -bool false
# defaults write NSGlobalDomain AppleKeyboardUIMode -int 2 # What is 3?
defaults write -g ApplePressAndHoldEnabled -bool false
defaults write -g KeyRepeat -int 2
# TODO: Set delay, try to set mouse and trackpad sensitivity.

# Finder.
defaults write -g AppleShowAllExtensions -bool true
defaults write -g NSDocumentSaveNewDocumentsToCloud -bool false
defaults write -g NSNavPanelExpandedStateForSaveMode -bool true
defaults write -g NSNavPanelExpandedStateForSaveMode2 -bool true
defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true
defaults write com.apple.desktopservices DSDontWriteUSBStores -bool true
defaults write com.apple.finder ShowPathbar -bool true
defaults write com.apple.PowerChime ChimeOnAllHardware -bool true
open /System/Library/CoreServices/PowerChime.app

# ForkLift.
# defaults write -g NSFileViewer -string com.binarynights.ForkLift-3;
# defaults write com.apple.LaunchServices/com.apple.launchservices.secure LSHandlers -array-add '{LSHandlerContentType="public.folder";LSHandlerRoleAll="com.binarynights.ForkLift-3";}'

# iTerm2.
defaults write com.googlecode.iterm2.plist PrefsCustomFolder -string "$HOME/.config/iTerm"
defaults write com.googlecode.iterm2.plist LoadPrefsFromCustomFolder -bool true

# Google Chrome.
defaults write com.google.Chrome AppleEnableMouseSwipeNavigateWithScrolls -bool false
defaults write com.google.Chrome AppleEnableSwipeNavigateWithScrolls -bool false

defaults write com.apple.mail DisableInlineAttachmentViewing -bool true

# Disable rearranging Spaces based on MRU
defaults write com.apple.dock mru-spaces -bool false
killall Dock

defaults write com.apple.finder QuitMenuItem -bool true
killall Finder

# Visual Studio Code
mkdir -p "$HOME/Library/Application Support/Code/User"
cd "$HOME/Library/Application Support/Code/User"
ln -s "$HOME/.config/Code/User/keybindings.json" keybindings.json
ln -s "$HOME/.config/Code/User/settings.json" settings.json
